# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/**'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-elegant
Style/GlobalVars:
  Enabled: false
Style/TopLevelMethodDefinition:
  Enabled: false
Naming/MethodParameterName:
  AllowedNames:
    - as
    - at
    - by
    - cc
    - db
    - fb
    - id
    - if
    - in
    - io
    - ip
    - of
    - 'on'
    - os
    - pp
    - to
