# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: markdown-lint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore: ['paper/**', 'sandbox/**']
concurrency:
  group: markdown-lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  markdown-lint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: DavidAnson/markdownlint-cli2-action@b847b0e2798e09594353ac3d92f6222621a4d870
